name: CI Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install clang-tools
      run: |
        sudo apt install clang-format --no-install-recommends -y

    - name: Check formatting
      env:
        SHA_BASE: ${{ github.event.pull_request.base.sha }}
      run: |
        OUTPUT=$(git diff -U0 --no-color ${SHA_BASE} | python3 ./utilities/script/clang-format-diff.py -p1 -sort-includes)
        if [ ! "${OUTPUT}" = "" ]; then echo "${OUTPUT}"; exit 1; fi

  build-firmwares:
    needs: check-format
    strategy:
      fail-fast: false
      matrix:
        firmware: [main, initial]
        target: [release, dev]
        platform: [device, simulator]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - shell: bash
      env:
        GET_KEY: ${{ secrets.GET_KEY }}
        PLATFORM: ${{ matrix.platform }}
      run: |
        if [[ "${PLATFORM}" == "device" ]]; then
          $GET_KEY && cp privatekeypairs/*.h utilities/script/
        fi

    - name: Install dependencies
      env:
        PLATFORM: ${{ matrix.platform }}
      run: |
        if [[ "${PLATFORM}" == "simulator" ]]; then
          sudo apt install ninja-build cmake libsdl2-dev --no-install-recommends -y
        else
          sudo apt install gcc-arm-none-eabi libnewlib-arm-none-eabi ninja-build cmake python3 pip --no-install-recommends -y
          pip install -r utilities/script/requirements.txt
        fi

    # Todo: run clang-tidy

    - name: Build binaries
      run: ./utilities/build.sh ${{ matrix.firmware }} ${{ matrix.target }} ${{ matrix.platform }}
